site_name: Spy's cool Site
nav:
  - Home: home.md
  - About: about.md
theme:
  name: material
  palette: 
    scheme: default
    primary: light green
    accent: indigo
  
site_url: https://goodcoolspysites.com/docs